apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-labels
  labels:
    app: nginx
    environment: test
spec:
  containers:
  - name: nginx
    image: nginx:1.22
    ports:
    - containerPort: 80
