apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-deployment
  namespace: dev
  labels:
    app: test1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - name: http
          containerPort: 80
